// Writes a ForgeResult to disk as a ready-to-install wp-content/ tree, plus an
// INSTALL.md and a manifest. Optionally zips the wp-content directory.
import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";
import type { Config } from "./config";
import type { ForgeResult } from "./types";
import { ensureDir, writeFileSafe, log } from "./util";

export interface WriteResult {
  outDir: string;
  themeDir: string;
  pluginsDir: string;
  fileCount: number;
  zipPath?: string;
}

export function writeForge(result: ForgeResult, cfg: Config): WriteResult {
  const outDir = result.outDir;
  if (fs.existsSync(outDir)) {
    fs.rmSync(outDir, { recursive: true, force: true });
  }
  ensureDir(outDir);

  const wpContent = path.join(outDir, "wp-content");
  const themeDir = path.join(wpContent, "themes", result.contract.themeSlug);
  const pluginsDir = path.join(wpContent, "plugins");
  let fileCount = 0;

  // Theme
  for (const f of result.themeFiles) {
    writeFileSafe(path.join(themeDir, f.path), f.content);
    fileCount++;
  }

  // Plugins (each in its own directory)
  for (const plugin of result.plugins) {
    for (const f of plugin.files) {
      writeFileSafe(path.join(pluginsDir, plugin.slug, f.path), f.content);
      fileCount++;
    }
  }

  // Generated featured images live inside the seed plugin so the seeder can
  // sideload them into the media library on activation.
  const seedSlug = result.plugins.find((p) => p.slug.endsWith("-seed"))?.slug;
  if (seedSlug) {
    for (const img of result.images) {
      const abs = path.join(pluginsDir, seedSlug, img.path);
      ensureDir(path.dirname(abs));
      fs.writeFileSync(abs, img.data);
      fileCount++;
    }
  }

  // Manifest (the plan, for transparency / re-runs)
  writeFileSafe(
    path.join(outDir, "wpforge-manifest.json"),
    JSON.stringify(
      {
        generatedWith: "wpforge",
        model: undefined,
        brief: result.brief,
        design: { ...result.design, styleCss: "[omitted]" },
        contract: result.contract,
        seedCounts: {
          pages: result.seed.pages.length,
          posts: result.seed.posts.length,
          cptItems: result.seed.cptItems.length,
          menuItems: result.seed.menu.items.length,
          images: result.images.length,
        },
        metrics: result.metrics,
      },
      null,
      2
    )
  );

  // INSTALL.md
  writeFileSafe(path.join(outDir, "INSTALL.md"), installMd(result));

  let zipPath: string | undefined;
  if (cfg.zip) {
    zipPath = tryZip(outDir, wpContent, result.contract.themeSlug);
  }

  return { outDir, themeDir, pluginsDir, fileCount, zipPath };
}

function tryZip(outDir: string, wpContent: string, slug: string): string | undefined {
  const zipPath = path.join(outDir, `${slug}.zip`);
  try {
    execFileSync("zip", ["-r", "-q", zipPath, "wp-content"], { cwd: outDir });
    return zipPath;
  } catch {
    log.warn("`zip` not available — skipped archive (folder output is ready to use).");
    return undefined;
  }
}

function installMd(r: ForgeResult): string {
  const plugins = r.plugins.map((p) => `- **${p.name}** (\`${p.slug}\`)`).join("\n");
  const contentModel = r.plugins.find((p) => p.slug.endsWith("-content-model"));
  const seedPlugin = r.plugins.find((p) => p.slug.endsWith("-seed"));
  const activationOrder = [
    contentModel ? `1. **${contentModel.name}** — registers custom post types & fields (activate first).` : null,
    ...r.plugins
      .filter((p) => p !== contentModel && p !== seedPlugin)
      .map((p, i) => `${(contentModel ? 2 : 1) + i}. **${p.name}**`),
    seedPlugin
      ? `${r.plugins.length}. **${seedPlugin.name}** — inserts all sample content, menu & front page (activate LAST). Requires an admin page load to run; visit wp-admin once after activating.`
      : null,
  ]
    .filter(Boolean)
    .join("\n");

  return `# ${r.brief.siteName}

${r.brief.tagline}

${r.brief.description}

Generated by **wpforge** (Cerebras + Qwen). Classic WordPress — no blocks.

## What's here

\`\`\`
wp-content/
  themes/${r.contract.themeSlug}/     ← the theme (${r.themeFiles.length} files)
  plugins/                            ← ${r.plugins.length} plugins
\`\`\`

Plugins:
${plugins}

## Install

1. Copy everything under \`wp-content/\` into your WordPress install's \`wp-content/\` directory (merging \`themes/\` and \`plugins/\`).
2. In **wp-admin → Appearance → Themes**, activate **${r.contract.themeName}**.
3. In **wp-admin → Plugins**, activate in this order:

${activationOrder}

4. Load any wp-admin page once so the seeder runs, then visit the site. The front page, primary menu (**${r.seed.menu.name}**), ${r.seed.pages.length} pages, ${r.seed.posts.length} posts and ${r.seed.cptItems.length} custom items will be in place.

### Notes
${
  r.images.length
    ? `- ${r.images.length} AI-generated featured images (Gemini) are bundled in the seeder plugin and attached automatically on seeding. They carry Google's invisible SynthID watermark.\n`
    : ""
}- Empty image areas render a themed vector placeholder automatically — set featured images to replace them.
- To re-run the seeder from scratch, delete the \`${r.contract.themeSlug.replace(/-/g, "_")}_seeded\` option (e.g. \`wp option delete ${r.contract.themeSlug.replace(/-/g, "_")}_seeded\`) and re-activate the seeder plugin.
- Requires WordPress 6.x and PHP 8.1+.
`;
}
